# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('content', wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'image_list', wagtail.wagtailcore.blocks.StructBlock([(b'image_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False))], label='Images')))], icon='image')), (b'aligned_image', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False))], icon='image', label='Aligned image'))])),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': '\u7b80\u5355\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
    ]
