# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0003_simplepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('content', wagtail.wagtailcore.fields.StreamField([(b'person', wagtail.wagtailcore.blocks.StructBlock([(b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())], icon='user'))])),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u533b\u751f\u56e2\u961f\u9875\u9762',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='simplepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'image_list', wagtail.wagtailcore.blocks.StructBlock([(b'image_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False))], label='Images')))], icon='image'))]),
        ),
    ]
