# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0005_categorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), (b'image_list_4', wagtail.wagtailcore.blocks.StructBlock([(b'image_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False))], label='\u56db\u5217\u56fe\u7247')))], icon='image')), (b'image_list_3', wagtail.wagtailcore.blocks.StructBlock([(b'image_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'caption', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, required=False))], label='\u4e09\u5217\u56fe\u7247')))], icon='image'))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='\u6807\u9898\u56fe\u7247'),
        ),
    ]
