# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-27 00:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180719_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentistspage',
            name='dentists',
            field=wagtail.wagtailcore.fields.StreamField([(b'page_title', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(label='\u5927\u6807\u9898', max_length=255, required=True)), (b'subtitle', wagtail.wagtailcore.blocks.CharBlock(label='\u5c0f\u6807\u9898', max_length=255, required=False))], icon='pilcrow', label='\u5927\u5c0f\u6807\u9898\u6a21\u5757')), (b'person', wagtail.wagtailcore.blocks.StructBlock([(b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())], icon='user'))], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dentistspage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'page_title', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(label='\u5927\u6807\u9898', max_length=255, required=True)), (b'subtitle', wagtail.wagtailcore.blocks.CharBlock(label='\u5c0f\u6807\u9898', max_length=255, required=False))], icon='pilcrow', label='\u5927\u5c0f\u6807\u9898\u6a21\u5757')), (b'person', wagtail.wagtailcore.blocks.StructBlock([(b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())], icon='user'))]),
        ),
    ]
