# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-27 01:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200527_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistspage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([(b'page_title', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(label='\u5927\u6807\u9898', max_length=255, required=True)), (b'subtitle', wagtail.wagtailcore.blocks.CharBlock(label='\u5c0f\u6807\u9898', max_length=255, required=False))], icon='pilcrow', label='\u5927\u5c0f\u6807\u9898\u6a21\u5757')), (b'underline_title', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(label='\u5927\u6807\u9898', max_length=255, required=True)), (b'subtitle', wagtail.wagtailcore.blocks.CharBlock(label='\u5c0f\u6807\u9898', max_length=255, required=False))], icon='pilcrow', label='\u4e0b\u5212\u7ebf\u6807\u9898\u6a21\u5757')), (b'html_paragraph', wagtail.wagtailcore.blocks.RawHTMLBlock(icon='code', label='HTML\u6bb5\u843d')), (b'html_quote', wagtail.wagtailcore.blocks.RawHTMLBlock(icon='openquote', label='HTML\u5f15\u7528')), (b'right_aligned_quote', wagtail.wagtailcore.blocks.TextBlock(icon='openquote', label='\u53f3\u5bf9\u9f50\u5f15\u7528')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', label='\u6bb5\u843d')), (b'image_with_caption', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='\u56fe\u7247')), (b'caption', wagtail.wagtailcore.blocks.CharBlock(label='\u56fe\u7247\u6807\u9898', max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, label='\u94fe\u63a5\u5230\u9875\u9762', required=False))], icon='image', label='\u5e26\u6807\u9898\u56fe\u7247')), (b'image_list', wagtail.wagtailcore.blocks.StructBlock([(b'image_list', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='\u56fe\u7247')), (b'caption', wagtail.wagtailcore.blocks.CharBlock(label='\u56fe\u7247\u6807\u9898', max_length=255, required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(can_choose_root=True, label='\u94fe\u63a5\u5230\u9875\u9762', required=False))], label='\u56fe\u7247')))], icon='image', label='\u56fe\u7247\u5217\u8868')), (b'html', wagtail.wagtailcore.blocks.RawHTMLBlock(icon='code', label='HTML\u4ee3\u7801'))]),
        ),
        migrations.AlterField(
            model_name='dentistspage',
            name='dentists',
            field=wagtail.wagtailcore.fields.StreamField([(b'person', wagtail.wagtailcore.blocks.StructBlock([(b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), (b'name', wagtail.wagtailcore.blocks.CharBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())], icon='user'))]),
        ),
    ]
